markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
gems: [jekyll-paginate]

blog:
    name: Xie Qiang                                               # 博客名称
    description: my blog                                         # 博客描述
    title: A little progress everyday.                                              # 网页标题
    url: qiangxie.github.io                                                # 博客地址
author:
    name: Xie Qiang                                               # 作者名称
    email: happyxieqiang@qq.com                                              # 邮箱地址
    weibo:                                               # 微博地址
    github:                                              # GitHub地址
    logo:                                                # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
